docs_dir: .
site_name: ClockworkEngine
nav:
  - Home: index.md
  - Engine:
    - engine/engine.md
    - engine/game.md
    - engine/scene.md
    - engine/entity.md
    - engine/camera.md
  - Animation:
    - animation/curves.md
    - animation/easer.md
    - animation/textures-animation.md
  - Audio:
    - audio/audio.md
  - Graphics:
    - graphics/graphics.md
  - Input:
    - input/input.md
  - Particles:
    - particles/particles.md
  - Shapes:
    - shapes/shapes.md
    - shapes/intersections.md
  - Tiles:
    - tiles/tiled-area.md
    - tiles/tiled-collider.md
    - tiles/tiled-world.md
  - UI:
    - ui/ui.md
  - Graphs:
    - graphs/graphs.md
  - Utilities:
    - utilities/transforms.md
    - utilities/timers.md
    - utilities/randomization.md
    - utilities/extensions.md
  - Windowing:
    - windowing/windowing.md
theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: amber
      foreground: "#FFFAFA"
      toggle: false
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
plugins:
  - awesome-pages:
      collapse_single_pages: true